Update Camera
add exception in import

copy image before save due to :
File "/usr/local/lib/python3.7/dist-packages/skvideo/io/ffmpeg.py", line 451, in writeFrame
    vid[vid > 255] = 255
ValueError: assignment destination is read-only